version: '3.5'

services:

    db:
        container_name: dentalsystem-db
        image: postgres
        ports:
            - 5438:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            - dental-system-network

    dentalsystemwebapi:
        container_name: dentalsystem-webapi
        image: dental-system-web-api
        build:
            context: .
            dockerfile: Presentation/DentalSystem.Presentation.Web.Api/Dockerfile
        environment:
            - ConnectionStrings__DentalSystemDbConnection=User ID=postgres;Password=postgres;Server=localhost;Port=5438;Database=DentalSystem_dev;Integrated Security=true; Pooling=true;
            - AllowedOrigins__0=https://localhost:5001
            - AllowedOrigins__1=http://localhost
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        network_mode: host
        depends_on:
            - db

    dentalsystemwebui:
        container_name: dentalsystem-webui
        image: dental-system-web-ui
        build:
            context: .
            dockerfile: Presentation/DentalSystem.Presentation.Web.UI/Dockerfile
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        network_mode: host
        depends_on:
            - dentalsystemwebapi

networks:
    dental-system-network:

volumes:
    database:
    data-protection: