version: '3.5'

services:

    db:
        container_name: dentalsystem-testdb
        image: postgres
        ports:
            - 5438:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./testdb:/var/lib/postgresql/data
        networks:
            - dental-system-network

    dentalsystemwebapi:
        container_name: dentalsystem-testwebapi
        image: dental-system-web-api
        build:
            context: .
            dockerfile: Presentation/DentalSystem.Presentation.Web.Api/Dockerfile
        environment:
            - ConnectionStrings__DentalSystemDbConnection=User ID=postgres;Password=postgres;Server=localhost;Port=5438;Database=DentalSystem_dev;Integrated Security=true; Pooling=true;
            - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
            - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
        network_mode: host
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        depends_on:
            - db

networks:
    dental-system-network:

volumes:
    testdb:
    data-protection: