version: '3.5'

services:

    db:
        image: postgres
        ports:
            - 5438:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./database:/var/lib/postgresql/data
        networks:
            - dental-system-network

    dentalsystemwebapi:
        image: dental-system-web-api
        build:
            context: .
            dockerfile: Presentation/DentalSystem.Presentation.Web.Api/Dockerfile
        ports:
            - 5555:5555
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - dental-system-network
        depends_on:
            - db

networks:
    dental-system-network:

volumes:
    database:
    data-protection: